name: hack4her_auth
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/
  fonts:
    - family: Lexend Deca
      fonts:
        - asset: assets/fonts/LexendDeca-Regular.ttf
        - asset: assets/fonts/LexendDeca-Bold.ttf 
        - asset: assets/fonts/LexendDeca-Medium.ttf
        - asset: assets/fonts/LexendDeca-Light.ttf
        - asset: assets/fonts/LexendDeca-SemiBold.ttf
  uses-material-design: true